import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// 调试信息：打印参数和模式
console.log("📋 构建参数:", process.argv);
console.log("🔧 构建模式:", prod ? "生产模式 (production)" : "开发模式 (development)");

// 统一输出到插件目录，由独立同步脚本复制到 Vault
const OUTPUT_DIR = ".";

console.log("📁 输出目录:", OUTPUT_DIR);

const cssOutputPlugin = () => ({
	name: "css-output-plugin",
	setup(build) {
		build.onEnd(async (result) => {
			const file = build.initialOptions.outfile;
			// rename css file
			const parent = path.dirname(file);
			const cssFileName = path.join(parent, "main.css");
			const newCssFileName = path.join(parent, "styles.css");
			
			try {
				if (fs.existsSync(cssFileName)) {
					fs.renameSync(cssFileName, newCssFileName);
					console.log(`✅ 已重命名 CSS 文件: ${newCssFileName}`);
				}
				
				// 生产模式：复制 manifest.json 到输出目录
				if (prod) {
					const manifestSource = path.resolve("manifest.json");
					const manifestTarget = path.resolve(parent, "manifest.json");
					if (fs.existsSync(manifestSource) && manifestSource !== manifestTarget) {
						fs.copyFileSync(manifestSource, manifestTarget);
						console.log(`✅ 已复制 manifest.json 到: ${manifestTarget}`);
					}

					console.log(`\n🎉 插件构建完成，产物目录: ${path.resolve(parent)}`);
				}
			} catch (e) {
				console.error("❌ CSS 处理失败:", e);
			}
		});
	},
});

const builtinExternals = [
	...builtins,
	...builtins.map((name) => `node:${name}`)
];

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [cssOutputPlugin()],
	external: [
		"obsidian",
		"electron",
		"@electron/remote",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinExternals,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(OUTPUT_DIR, "main.js"),
	minify: prod,
});

if (!fs.existsSync(OUTPUT_DIR)) {
	fs.mkdirSync(OUTPUT_DIR, { recursive: true });
	console.log(`📁 创建输出目录: ${OUTPUT_DIR}`);
}

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
