import type {
	ChatContextCompactionRange,
	ChatContextCompactionState,
	ChatMessage,
	ChatMessageMetadata,
	ChatOpenMode,
	ChatRequestTokenState,
	ChatRole,
	ChatSession,
	ChatSettings,
	ChatState,
	FileIntentAnalysis,
	FileRole,
	MessageManagementSettings,
	QuickAction,
	QuickActionPromptSource,
	QuickActionType,
	SelectedFile,
	SelectedFolder,
	SelectedItem,
	SelectedTextContext,
	ToolCall,
	LayoutMode,
	MultiModelMode,
	PlanSnapshot,
	PlanTask,
	PlanTaskStatus,
	ParallelResponseGroup,
	SubAgentExecutionState,
	SubAgentExecutionStatus,
} from 'src/domains/chat/types';
import type {
	ChatDomainLogger,
	ChatHostPorts,
	ChatMcpPort,
	ChatSkillDescriptor,
	ChatSkillsPort,
	ChatSkillsSnapshot,
	ChatToolSettingsPort,
	ChatVaultPort,
} from 'src/domains/chat/service';
import type { SkillSessionState } from 'src/domains/skills/session-state';
import {
	DEFAULT_CHAT_SETTINGS,
	DEFAULT_MESSAGE_MANAGEMENT_SETTINGS,
	normalizeMessageManagementSettings,
} from 'src/domains/chat/config';
import {
	createChatVaultPort,
	createChatHostPorts,
	isPinnedChatMessage,
} from 'src/domains/chat/service';

export type {
	ChatContextCompactionRange,
	ChatContextCompactionState,
	ChatMessage,
	ChatMessageMetadata,
	ChatOpenMode,
	ChatRequestTokenState,
	ChatRole,
	ChatSession,
	ChatSettings,
	ChatState,
	FileIntentAnalysis,
	FileRole,
	LayoutMode,
	MessageManagementSettings,
	MultiModelMode,
	ParallelResponseGroup,
	PlanSnapshot,
	PlanTask,
	PlanTaskStatus,
	QuickAction,
	QuickActionPromptSource,
	QuickActionType,
	SelectedFile,
	SelectedFolder,
	SelectedItem,
	SelectedTextContext,
	SubAgentExecutionState,
	SubAgentExecutionStatus,
	ToolCall,
	SkillSessionState,
}

export type {
	ChatDomainLogger,
	ChatHostPorts,
	ChatMcpPort,
	ChatSkillDescriptor,
	ChatSkillsPort,
	ChatSkillsSnapshot,
	ChatToolSettingsPort,
	ChatVaultPort,
}

export {
	DEFAULT_CHAT_SETTINGS,
	DEFAULT_MESSAGE_MANAGEMENT_SETTINGS,
	createChatHostPorts,
	createChatVaultPort,
	isPinnedChatMessage,
	normalizeMessageManagementSettings,
}
